[package]
name = "rustomp"
version = "0.1.0"
authors = ["Joshua Jones <joshua.jones.software@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
